[nixpacks]
  language = "node"

[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[start]
cmd = "node index.js"

apt-get update && apt-get install -y --no-install-recommends \
  libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 \
  libpangocairo-1.0-0 libxss1 libgtk-3-0 libxshmfence1 libglu1